attributes:
  emc_username:
    value: "username"
    label: "XMS username"
    description: "EMC XtremIO XMS username."
    weight: 75
    type: "text"
    regex:
      source: '\S'
      error: "Username field cannot be empty"
  emc_password:
    value: "password"
    label: "XMS password"
    description: "EMC XtremIO XMS password."
    weight: 80
    type: "password"
    regex:
      source: '\S'
      error: "Password field cannot be empty"
  emc_sc1_ip:
    value: ""
    label: "SC1 IP"
    description: "EMC XtremIO SC1 IP address."
    weight: 90
    type: "text"
    regex:
      source: '^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
      error: "Specify valid IPv4 address"
  emc_sc2_ip:
    value: ""
    label: "SC2 IP"
    description: "EMC XtremIO SC2 IP address."
    weight: 90
    type: "text"
    regex:
      source: '^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
      error: "Specify valid IPv4 address"
  emc_cluster_name:
    value: ""
    label: "EMC XtremIO cluster name"
    description: "EMC XtremIO cluster name (optional)"
    weight: 95
    type: "text"
