attributes:
  metadata:
    # Settings group can be one of "general", "security", "compute", "network",
    # "storage", "logging", "openstack_services" and "other".
    group: 'storage'

  emc_username:
    value: "username"
    label: "XMS username"
    description: "EMC XtremIO XMS username."
    weight: 75
    type: "text"
    regex:
      source: '\S'
      error: "Username field cannot be empty"
  emc_password:
    value: "password"
    label: "XMS password"
    description: "EMC XtremIO XMS password."
    weight: 80
    type: "password"
    regex:
      source: '\S'
      error: "Password field cannot be empty"
  emc_xms_ip:
    value: ""
    label: "XMS IP"
    description: "EMC XtremIO XMS IP address."
    weight: 90
    type: "text"
    regex:
      source: '^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
      error: "Specify valid IPv4 address"
  emc_cluster_name:
    value: ""
    label: "XtremIO cluster name"
    description: "EMC XtremIO cluster name (optional)"
    weight: 95
    type: "text"
