attributes:
  metadata:
    # Settings group can be one of "general", "security", "compute", "network",
    # "storage", "logging", "openstack_services" and "other".
    group: 'storage'
  xtremio_protocol:
    value: 'FC'
    label: 'Protocol Type'
    description: ''
    weight: 25
    type: 'radio'
    values:
      - data: 'FC'
        label: 'Fibre Channel'
        description: 'Use Fibre Channel for XtremIO block storage'
      - data: 'iSCSI'
        label: 'iSCSI'
        description: 'Use iSCSI for XtremIO block storage'
  emc_username:
    value: "username"
    label: "XMS username"
    description: "EMC XtremIO XMS username."
    weight: 75
    type: "text"
    regex:
      source: '\S'
      error: "Username field cannot be empty"
  emc_password:
    value: "password"
    label: "XMS password"
    description: "EMC XtremIO XMS password."
    weight: 80
    type: "password"
    regex:
      source: '\S'
      error: "Password field cannot be empty"
  emc_xms_ip:
    value: ""
    label: "XMS Address"
    description: "EMC XtremIO XMS URL."
    weight: 90
    type: "text"
    regex:
      source: '\S'
      error: "XMS URL cannot be empty"
  emc_cluster_name:
    value: ""
    label: "XtremIO cluster name"
    description: "EMC XtremIO cluster name (optional)"
    weight: 95
    type: "text"
