#!/bin/bash
set -eux

ROOT="$(dirname `readlink -f $0`)"
DEB_REPO="${ROOT}"/repositories/ubuntu/
mkdir -p $DEB_REPO

# Downloads needed RPM or DEB packages
function download {
    case "$1" in
        deb) REPO=$DEB_REPO;;
    esac
    shift

    while [ $# -gt 0 ]; do
        FILE=$(basename "$1")
        wget -qO - $1 > "$REPO/$FILE"
        shift
    done
}

download deb http://archive.ubuntu.com/ubuntu/pool/main/m/multipath-tools/multipath-tools_0.4.9-3ubuntu5_amd64.deb \
             http://archive.ubuntu.com/ubuntu/pool/main/o/open-iscsi/open-iscsi_2.0.873-3ubuntu9_amd64.deb

